const actionTypes = {
  LOADING: "START_LOADING",
  SUCCESS_LOADING: "SUCCESS_LOADING",
  ERROR_LOADING: "ERROR_LOADING",
  SET_PAGE: "SET_PAGE",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  CREATE_ACCOUNT_ERROR: "CREATE_ACCOUNT_ERROR",
  SUCCESS_LOGIN: "SUCCESS_LOGIN",
  LOGOUT: "LOGOUT",
  SUCCESS_CHANGE: "SUCCESS_CHANGE",
  SET_USER_PROCESSING: "SET_USER_PROCESSING",
};

export default actionTypes;
